version: 2.1
executors:
  # ここに好きな名前で executor を定義できる
  default:
    working_directory: ~/workspace
    docker:
      - image: node:8.15.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - persist_to_workspace:
          root: . # workspaceのrootパス（絶対パスかworking_directoryからの相対パス）
          paths:
            - . # 共有するパス（絶対パスかrootからの相対パス）
  test:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
      - run:
          name: Post Coveralls
          command: yarn test:coveralls
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set Version
          command: yarn upload:version
      - run:
          name: Install zip
          command: apt-get update -y && apt-get install -y zip
      - run:
          name: Pack ZIP
          command: yarn upload:pack
      - run:
          name: Upload & Publish
          command: yarn upload


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
